# Generated by Django 3.0.6 on 2020-05-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myeducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('study', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=100)),
                ('branchIs', models.BooleanField(default=False)),
                ('cgpa', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dec', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
